### ISSUE TITLE
Error while runing simulation

### ISSUE THREAD

**Issue by bastiencarreres** [LSSTDESC/sn_pipe#2]
Hi,
I try to run a simulation from a yaml file but it's always finnish with the error code : 

>` File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_tools/sn_process.py", line 278, in processPatch
    idx = pixels['pixRA'] > pointing['minRA']
TypeError: 'NoneType' object is not subscriptable

Before this error I have :

[300rows x 8 columns]
starting
pointings 300
go for multiprocessing 9 <bound method Process.processPatch of <sn_tools.sn_process.Process object at 0x7f61774cfb90>>          RA        Dec  radius_RA  ...  maxRA     minDec     maxDec
2702  326.0  29.712134        4.0  ...  328.0  27.683115  31.741153
2703  326.0  33.770172        4.0  ...  328.0  31.741153  35.799192
2704  326.0  37.828211        4.0  ...  328.0  35.799192  39.857230
2705  326.0  41.886249        4.0  ...  328.0  39.857230  43.915268
2706  330.0 -87.970981        4.0  ...  332.0 -90.000000 -85.941962
...     ...        ...        ...  ...    ...        ...        ...
2998  362.0  25.654095        4.0  ...  364.0  23.625076  27.683115
2999  362.0  29.712134        4.0  ...  364.0  27.683115  31.741153
3000  362.0  33.770172        4.0  ...  364.0  31.741153  35.799192
3001  362.0  37.828211        4.0  ...  364.0  35.799192  39.857230
3002  362.0  41.886249        4.0  ...  364.0  39.857230  43.915268

[301 rows x 8 columns]
starting
pointings 301
Process Subprocess-9:
Traceback (most recent call last):` 

Have you an answer to my problem?
Thanks you,
Bastien Carreres

**Comment by pgris** [comment]
Hi, 

thank you for using sn_pipe. Would you mind providing the commands you have used (from the git clone) so that I can try to reproduce the problem?

Philippe

**Comment by bastiencarreres** [comment]
Thank you for your response

I use :  
python run_scripts/simulation/run_simulation_from_yaml.py --RAmin=0.0 --RAmax=360.0 --config_yaml=input/simulation/param_simulation_example.yaml

python run_scripts/simulation/run_simulation_from_yaml.py --config_yaml=input/simulation/param_simulation_example.yaml

and

python run_scripts/simulation/run_simulation_from_yaml.py --RAmin 0. --RAmax 360. --Decmin -24. --Decmax -20. --config_yaml=input/simulation/param_simulation_example.yaml

This last doesn't crash but I fund no h5py file in the directory. I try to use desddfv1.4 and v1.5 and I change WFD to DD but error is the same.

**Comment by pgris** [comment]
Would you mind trying adding --npixels -1 in the command line? It sounds likeyou are running with --npixels 0 (default)

**Comment by bastiencarreres** [comment]
I've tried 
python run_scripts/simulation/run_simulation_from_yaml.py --npixels -1 --config_yaml=input/simulation/param_simulation_example.yaml

I still have the error message :
[301 rows x 8 columns]
starting
pointings 301
Process Subprocess-9:
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_tools/sn_process.py", line 278, in processPatch
    idx = pixels['pixRA'] > pointing['minRA']
TypeError: 'NoneType' object is not subscriptable

But it's fllowed by some : nsn from rate [number] (most of the number are 0)
and by a new error :

Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 182, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

and 

Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 534, in simuLoop
    self.dump(list_lc, season, iproc, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 557, in dump
    self.writeLC(self.SNID[j], lc, season, j, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 457, in writeLC
    compression=True)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/table/table.py", line 2594, in write
    io_registry.write(self, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/misc/hdf5.py", line 290, in write_table_hdf5
    f = h5py.File(output, 'a' if append else 'w')
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/renoir/carreres/CosmoSoft/LSST/OutPut/descddf1.5/LC_Descddf1.5_6.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

However some h5py files have been created in the output directory.

**Comment by pgris** [comment]
Part of the problem is due to the fact that you are accessing areas with no data. I have included a protection for that in the code. Please reinstall sn_pipe from master and rerun.

**Comment by bastiencarreres** [comment]
After git pull and python pip_sn_pack.py --action install --package=all, the errors are still here :

######1st error#######

Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_tools/sn_process.py", line 278, in processPatch
    idx = pixels['pixRA'] > pointing['minRA']
TypeError: 'NoneType' object is not subscriptable

######2nd error#######

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 534, in simuLoop
    self.dump(list_lc, season, iproc, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 557, in dump
    self.writeLC(self.SNID[j], lc, season, j, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 457, in writeLC
    compression=True)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/table/table.py", line 2594, in write
    io_registry.write(self, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/misc/hdf5.py", line 290, in write_table_hdf5
    f = h5py.File(output, 'a' if append else 'w')
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/renoir/carreres/CosmoSoft/LSST/OutPut/descddf1.5/LC_Descddf1.5_6.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
Process Subprocess:
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 182, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 534, in simuLoop
    self.dump(list_lc, season, iproc, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 557, in dump
    self.writeLC(self.SNID[j], lc, season, j, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 457, in writeLC
    compression=True)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/table/table.py", line 2594, in write
    io_registry.write(self, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/misc/hdf5.py", line 290, in write_table_hdf5
    f = h5py.File(output, 'a' if append else 'w')
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/renoir/carreres/CosmoSoft/LSST/OutPut/descddf1.5/LC_Descddf1.5_6.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

**Comment by pgris** [comment]
Try ro run with Decmin=-60 Decmax=0.

**Comment by bastiencarreres** [comment]
The first error seems to be resolved with Decmin=-60 and Decmax=0 but I still have the second type of error :

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_14/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 534, in simuLoop
    self.dump(list_lc, season, iproc, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 557, in dump
    self.writeLC(self.SNID[j], lc, season, j, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 457, in writeLC
    compression=True)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/table/table.py", line 2594, in write
    io_registry.write(self, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/misc/hdf5.py", line 290, in write_table_hdf5
    f = h5py.File(output, 'a' if append else 'w')
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/renoir/carreres/CosmoSoft/LSST/OutPut/descddf1.5/LC_Descddf1.5_7.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

**Comment by pgris** [comment]
All of this point to fact that you are **not** using the latest version of sn_pipe. Did you install eveything from scratch as I advised?

Please do the following:
- uninstall everything
- remove the working directory
- reinstall everything 

It seems that you are mixing code versions. So let us start from a clean environment to have a better understanding of what is going on.

**Comment by bastiencarreres** [comment]
I have uninstall everything, completely delete the sn_pipe directory and I have reinstall everything : now the error with " idx = pixels['pixRA'] > pointing['minRA']" no longer appear even if I don't set Decmin -60 et Decmax 0 . The second error appear only if I use multiprocessing.

**Comment by pgris** [comment]
This is very strange: I managed to run on 12 procs with no problem. How do you use multiprocessing?

**Comment by bastiencarreres** [comment]
I've tried 2 differents ways : 
- just set the value of nproc to 5 in the yaml file and run the python script
- use mpiexec -n 5 to run the script
The 2 ways give the same type of error : 

Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_15/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_15/python/miniconda3-4.7.12/envs/lsst-scipipe-984c9f7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 534, in simuLoop
    self.dump(list_lc, season, iproc, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 557, in dump
    self.writeLC(self.SNID[j], lc, season, j, meta_lc)
  File "/renoir/carreres/.local/lib/python3.7/site-packages/sn_simu_wrapper/sn_simu.py", line 457, in writeLC
    compression=True)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/table/table.py", line 2594, in write
    io_registry.write(self, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/registry.py", line 560, in write
    writer(data, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/astropy/io/misc/hdf5.py", line 290, in write_table_hdf5
    f = h5py.File(output, 'a' if append else 'w')
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/renoir/carreres/CosmoSoft/LSST/OutPut/baseline1.4_multiproc/LC_baseline1.4_0.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

**Comment by pgris** [comment]
On which machine are you running? Linux ? Which version?
What do the following command give as result?
- echo $LSST_HOME
- echo $LSST_SIMS_DIR
- echo $LSST_CONDA_ENV_NAME

**Comment by bastiencarreres** [comment]
I'm running on mardec at CPPM, the OS is Scientific Linux 7.8 (Nitrogen)
The results of the commands:
(lsst-scipipe-984c9f7) -bash-4.2$ echo $LSST_HOME
/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_15
(lsst-scipipe-984c9f7) -bash-4.2$ echo $LSST_SIMS_DIR
/cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_15/stack/miniconda3-4.7.12-984c9f7/Linux64/lsst_sims/2.13.0.sims-3-gec5618e+56
(lsst-scipipe-984c9f7) -bash-4.2$ echo $LSST_CONDA_ENV_NAME
lsst-scipipe-984c9f7

I setup the environment by source setup_release.sh file in sn_pipe.

**Comment by pgris** [comment]
Ok. thanks. So the environment is the same. Would you mind giving the version of sn_tools and sn_simu_wrapper you are using?

**Comment by bastiencarreres** [comment]
The pack_version.txt give:
# list of packages and tagged github version
sn_metrics v1.0.0
sn_simulation v1.0.0
sn_fit_lc v1.0.0
sn_plotters v1.0.0

and pip freeze | grep sn- give:
sn-fit-lc @ git+https://github.com/lsstdesc/sn_fit_lc.git@30e5cbee1b18212de2471ab33f0b3e1fb1a0e897
sn-metrics @ git+https://github.com/lsstdesc/sn_metrics.git@86bdbaaf6ddd3770598cfb1163b8037e83da0e5c
sn-pipe==1.0.0
sn-plotters @ git+https://github.com/lsstdesc/sn_plotters.git@6248a9831150cf7ac7922154a16026785a478110
sn-simulation @ git+https://github.com/lsstdesc/sn_simulation.git@0ddadcfaf1647337bccaf1eb77efce23b42b5fe4
sn-stackers @ git+https://github.com/lsstdesc/sn_stackers.git@15b4fd05001e5704c243cd0b3145769ead817e04
sn-tools @ git+https://github.com/lsstdesc/sn_tools.git@54dc9d5961a0acfc1d16a19632f942c29046041f

I didn't find sn_simu_wrapper.

**Comment by pgris** [comment]
This is not the information I would need. To know the package version, you can use ipython. An example is given here:
ipython
import sn_simu_wrapper
sn_simu_wrapper.\_\_version\_\_

The last line should give you the version number

**Comment by bastiencarreres** [comment]
Sorry,
The version of  sn_simu_wrapper is : v1.0.0 and the version of sn_tools is: v1.0.1.
